// priority: 2147483647

const ToolPartItem = Java.loadClass('slimeknights.tconstruct.library.tools.part.ToolPartItem')
const ForgeRegistries = Java.loadClass('net.minecraftforge.registries.ForgeRegistries')
const MaterialRegistry = Java.loadClass('slimeknights.tconstruct.library.materials.MaterialRegistry')
const MaterialId = Java.loadClass('slimeknights.tconstruct.library.materials.definition.MaterialId')
const MaterialVariant = Java.loadClass('slimeknights.tconstruct.library.materials.definition.MaterialVariant')
const ModifierId = Java.loadClass('slimeknights.tconstruct.library.modifiers.ModifierId')
const ModifierNBT = Java.loadClass('slimeknights.tconstruct.library.tools.nbt.ModifierNBT')
const ResourceColorManager = Java.loadClass('slimeknights.mantle.client.ResourceColorManager')
const TextColor = Java.loadClass('net.minecraft.network.chat.TextColor')
const ToolStack = Java.loadClass('slimeknights.tconstruct.library.tools.nbt.ToolStack')
const TiCToolDefinitions = Java.loadClass('slimeknights.tconstruct.tools.ToolDefinitions')
const MaterialNBT = Java.loadClass('slimeknights.tconstruct.library.tools.nbt.MaterialNBT')
const MaterialNBTBuilder = Java.loadClass('slimeknights.tconstruct.library.tools.nbt.MaterialNBT$Builder')