name: Build Modpack

on:
    push:
        branches: ["1.20.1"]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
              - uses: actions/checkout@v4
              - name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.x'
              - name: Run build script
                run: python build.py build --build-version ${{ github.sha }}
              - name: Upload Artifact
                uses: actions/upload-artifact@v4
                with:
                    name: "Built modpack ${{ github.sha }}"
                    path: '*.zip'
    
    cleanup_artifacts:
        needs: build
        runs-on: ubuntu-latest

        steps:
          - name: Remove old artifacts
            uses: c-hive/gha-remove-artifacts@v1.4.0
            with:
                age: 0
                skip-recent: 1
