name: Cleanup Old Artifacts

on:
    schedule:
          - cron: '0 1 * * *'
    workflow_dispatch:
jobs:
    remove-old-artifacts:
        runs-on: ubuntu-latest
        steps:
          - name: Remove old artifacts
            uses: c-hive/gha-remove-artifacts@v1.4.0
            with:
                age: "0"
                skip-recent: 1